// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Infos-ETC.proto

public final class InfosETC {
  private InfosETC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Infos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    java.util.List<InfosETC.Infos.Information> 
        getInformationList();
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    InfosETC.Infos.Information getInformation(int index);
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    int getInformationCount();
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    java.util.List<? extends InfosETC.Infos.InformationOrBuilder> 
        getInformationOrBuilderList();
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    InfosETC.Infos.InformationOrBuilder getInformationOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Infos}
   */
  public  static final class Infos extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Infos)
      InfosOrBuilder {
    // Use Infos.newBuilder() to construct.
    private Infos(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Infos() {
      information_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Infos(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                information_ = new java.util.ArrayList<InfosETC.Infos.Information>();
                mutable_bitField0_ |= 0x00000001;
              }
              information_.add(
                  input.readMessage(InfosETC.Infos.Information.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          information_ = java.util.Collections.unmodifiableList(information_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InfosETC.internal_static_Infos_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InfosETC.internal_static_Infos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InfosETC.Infos.class, InfosETC.Infos.Builder.class);
    }

    public interface InformationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Infos.Information)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bytes ubMac = 1;</code>
       */
      com.google.protobuf.ByteString getUbMac();

      /**
       * <code>optional uint32 time = 2;</code>
       */
      int getTime();

      /**
       * <pre>
       *发卡方标识
       * </pre>
       *
       * <code>optional bytes cardIssuerID = 10;</code>
       */
      com.google.protobuf.ByteString getCardIssuerID();

      /**
       * <pre>
       *卡片类型
       * </pre>
       *
       * <code>optional bytes cardType = 11;</code>
       */
      com.google.protobuf.ByteString getCardType();

      /**
       * <pre>
       *卡片版本号
       * </pre>
       *
       * <code>optional bytes cardVer = 12;</code>
       */
      com.google.protobuf.ByteString getCardVer();

      /**
       * <pre>
       *卡片网络编号
       * </pre>
       *
       * <code>optional bytes cardNetID = 13;</code>
       */
      com.google.protobuf.ByteString getCardNetID();

      /**
       * <pre>
       *用户卡内部编号
       * </pre>
       *
       * <code>optional bytes cardInternalID = 14;</code>
       */
      com.google.protobuf.ByteString getCardInternalID();

      /**
       * <pre>
       *启用时间
       * </pre>
       *
       * <code>optional bytes enableTime = 15;</code>
       */
      com.google.protobuf.ByteString getEnableTime();

      /**
       * <pre>
       *到期时间
       * </pre>
       *
       * <code>optional bytes expiredTime = 16;</code>
       */
      com.google.protobuf.ByteString getExpiredTime();

      /**
       * <pre>
       *	车牌号码
       * </pre>
       *
       * <code>optional bytes carNO = 17;</code>
       */
      com.google.protobuf.ByteString getCarNO();

      /**
       * <pre>
       *用户类型
       * </pre>
       *
       * <code>optional bytes userType = 18;</code>
       */
      com.google.protobuf.ByteString getUserType();

      /**
       * <pre>
       *	车牌颜色
       * </pre>
       *
       * <code>optional bytes carColor = 19;</code>
       */
      com.google.protobuf.ByteString getCarColor();

      /**
       * <pre>
       *车型
       * </pre>
       *
       * <code>optional bytes carModel = 20;</code>
       */
      com.google.protobuf.ByteString getCarModel();

      /**
       * <pre>
       *持卡人姓名
       * </pre>
       *
       * <code>optional bytes cardHolderName = 21;</code>
       */
      com.google.protobuf.ByteString getCardHolderName();

      /**
       * <pre>
       *持卡人证件号码
       * </pre>
       *
       * <code>optional bytes cardHolderID = 22;</code>
       */
      com.google.protobuf.ByteString getCardHolderID();

      /**
       * <pre>
       *持卡人证件类型
       * </pre>
       *
       * <code>optional bytes cardHolderIDType = 23;</code>
       */
      com.google.protobuf.ByteString getCardHolderIDType();

      /**
       * <pre>
       *OBU信息,合同
       * </pre>
       *
       * <code>optional bytes obuInfo = 24;</code>
       */
      com.google.protobuf.ByteString getObuInfo();

      /**
       * <pre>
       *文件0019，高速最后收费站信息
       * </pre>
       *
       * <code>optional bytes file0019 = 25;</code>
       */
      com.google.protobuf.ByteString getFile0019();

      /**
       * <pre>
       * obu类型
       * </pre>
       *
       * <code>optional bytes obuType = 26;</code>
       */
      com.google.protobuf.ByteString getObuType();

      /**
       * <pre>
       *经纬度信息
       * </pre>
       *
       * <code>optional bytes gps = 27;</code>
       */
      com.google.protobuf.ByteString getGps();
    }
    /**
     * Protobuf type {@code Infos.Information}
     */
    public  static final class Information extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Infos.Information)
        InformationOrBuilder {
      // Use Information.newBuilder() to construct.
      private Information(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private Information() {
        ubMac_ = com.google.protobuf.ByteString.EMPTY;
        time_ = 0;
        cardIssuerID_ = com.google.protobuf.ByteString.EMPTY;
        cardType_ = com.google.protobuf.ByteString.EMPTY;
        cardVer_ = com.google.protobuf.ByteString.EMPTY;
        cardNetID_ = com.google.protobuf.ByteString.EMPTY;
        cardInternalID_ = com.google.protobuf.ByteString.EMPTY;
        enableTime_ = com.google.protobuf.ByteString.EMPTY;
        expiredTime_ = com.google.protobuf.ByteString.EMPTY;
        carNO_ = com.google.protobuf.ByteString.EMPTY;
        userType_ = com.google.protobuf.ByteString.EMPTY;
        carColor_ = com.google.protobuf.ByteString.EMPTY;
        carModel_ = com.google.protobuf.ByteString.EMPTY;
        cardHolderName_ = com.google.protobuf.ByteString.EMPTY;
        cardHolderID_ = com.google.protobuf.ByteString.EMPTY;
        cardHolderIDType_ = com.google.protobuf.ByteString.EMPTY;
        obuInfo_ = com.google.protobuf.ByteString.EMPTY;
        file0019_ = com.google.protobuf.ByteString.EMPTY;
        obuType_ = com.google.protobuf.ByteString.EMPTY;
        gps_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Information(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {

                ubMac_ = input.readBytes();
                break;
              }
              case 16: {

                time_ = input.readUInt32();
                break;
              }
              case 82: {

                cardIssuerID_ = input.readBytes();
                break;
              }
              case 90: {

                cardType_ = input.readBytes();
                break;
              }
              case 98: {

                cardVer_ = input.readBytes();
                break;
              }
              case 106: {

                cardNetID_ = input.readBytes();
                break;
              }
              case 114: {

                cardInternalID_ = input.readBytes();
                break;
              }
              case 122: {

                enableTime_ = input.readBytes();
                break;
              }
              case 130: {

                expiredTime_ = input.readBytes();
                break;
              }
              case 138: {

                carNO_ = input.readBytes();
                break;
              }
              case 146: {

                userType_ = input.readBytes();
                break;
              }
              case 154: {

                carColor_ = input.readBytes();
                break;
              }
              case 162: {

                carModel_ = input.readBytes();
                break;
              }
              case 170: {

                cardHolderName_ = input.readBytes();
                break;
              }
              case 178: {

                cardHolderID_ = input.readBytes();
                break;
              }
              case 186: {

                cardHolderIDType_ = input.readBytes();
                break;
              }
              case 194: {

                obuInfo_ = input.readBytes();
                break;
              }
              case 202: {

                file0019_ = input.readBytes();
                break;
              }
              case 210: {

                obuType_ = input.readBytes();
                break;
              }
              case 218: {

                gps_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InfosETC.internal_static_Infos_Information_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InfosETC.internal_static_Infos_Information_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InfosETC.Infos.Information.class, InfosETC.Infos.Information.Builder.class);
      }

      public static final int UBMAC_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString ubMac_;
      /**
       * <code>optional bytes ubMac = 1;</code>
       */
      public com.google.protobuf.ByteString getUbMac() {
        return ubMac_;
      }

      public static final int TIME_FIELD_NUMBER = 2;
      private int time_;
      /**
       * <code>optional uint32 time = 2;</code>
       */
      public int getTime() {
        return time_;
      }

      public static final int CARDISSUERID_FIELD_NUMBER = 10;
      private com.google.protobuf.ByteString cardIssuerID_;
      /**
       * <pre>
       *发卡方标识
       * </pre>
       *
       * <code>optional bytes cardIssuerID = 10;</code>
       */
      public com.google.protobuf.ByteString getCardIssuerID() {
        return cardIssuerID_;
      }

      public static final int CARDTYPE_FIELD_NUMBER = 11;
      private com.google.protobuf.ByteString cardType_;
      /**
       * <pre>
       *卡片类型
       * </pre>
       *
       * <code>optional bytes cardType = 11;</code>
       */
      public com.google.protobuf.ByteString getCardType() {
        return cardType_;
      }

      public static final int CARDVER_FIELD_NUMBER = 12;
      private com.google.protobuf.ByteString cardVer_;
      /**
       * <pre>
       *卡片版本号
       * </pre>
       *
       * <code>optional bytes cardVer = 12;</code>
       */
      public com.google.protobuf.ByteString getCardVer() {
        return cardVer_;
      }

      public static final int CARDNETID_FIELD_NUMBER = 13;
      private com.google.protobuf.ByteString cardNetID_;
      /**
       * <pre>
       *卡片网络编号
       * </pre>
       *
       * <code>optional bytes cardNetID = 13;</code>
       */
      public com.google.protobuf.ByteString getCardNetID() {
        return cardNetID_;
      }

      public static final int CARDINTERNALID_FIELD_NUMBER = 14;
      private com.google.protobuf.ByteString cardInternalID_;
      /**
       * <pre>
       *用户卡内部编号
       * </pre>
       *
       * <code>optional bytes cardInternalID = 14;</code>
       */
      public com.google.protobuf.ByteString getCardInternalID() {
        return cardInternalID_;
      }

      public static final int ENABLETIME_FIELD_NUMBER = 15;
      private com.google.protobuf.ByteString enableTime_;
      /**
       * <pre>
       *启用时间
       * </pre>
       *
       * <code>optional bytes enableTime = 15;</code>
       */
      public com.google.protobuf.ByteString getEnableTime() {
        return enableTime_;
      }

      public static final int EXPIREDTIME_FIELD_NUMBER = 16;
      private com.google.protobuf.ByteString expiredTime_;
      /**
       * <pre>
       *到期时间
       * </pre>
       *
       * <code>optional bytes expiredTime = 16;</code>
       */
      public com.google.protobuf.ByteString getExpiredTime() {
        return expiredTime_;
      }

      public static final int CARNO_FIELD_NUMBER = 17;
      private com.google.protobuf.ByteString carNO_;
      /**
       * <pre>
       *	车牌号码
       * </pre>
       *
       * <code>optional bytes carNO = 17;</code>
       */
      public com.google.protobuf.ByteString getCarNO() {
        return carNO_;
      }

      public static final int USERTYPE_FIELD_NUMBER = 18;
      private com.google.protobuf.ByteString userType_;
      /**
       * <pre>
       *用户类型
       * </pre>
       *
       * <code>optional bytes userType = 18;</code>
       */
      public com.google.protobuf.ByteString getUserType() {
        return userType_;
      }

      public static final int CARCOLOR_FIELD_NUMBER = 19;
      private com.google.protobuf.ByteString carColor_;
      /**
       * <pre>
       *	车牌颜色
       * </pre>
       *
       * <code>optional bytes carColor = 19;</code>
       */
      public com.google.protobuf.ByteString getCarColor() {
        return carColor_;
      }

      public static final int CARMODEL_FIELD_NUMBER = 20;
      private com.google.protobuf.ByteString carModel_;
      /**
       * <pre>
       *车型
       * </pre>
       *
       * <code>optional bytes carModel = 20;</code>
       */
      public com.google.protobuf.ByteString getCarModel() {
        return carModel_;
      }

      public static final int CARDHOLDERNAME_FIELD_NUMBER = 21;
      private com.google.protobuf.ByteString cardHolderName_;
      /**
       * <pre>
       *持卡人姓名
       * </pre>
       *
       * <code>optional bytes cardHolderName = 21;</code>
       */
      public com.google.protobuf.ByteString getCardHolderName() {
        return cardHolderName_;
      }

      public static final int CARDHOLDERID_FIELD_NUMBER = 22;
      private com.google.protobuf.ByteString cardHolderID_;
      /**
       * <pre>
       *持卡人证件号码
       * </pre>
       *
       * <code>optional bytes cardHolderID = 22;</code>
       */
      public com.google.protobuf.ByteString getCardHolderID() {
        return cardHolderID_;
      }

      public static final int CARDHOLDERIDTYPE_FIELD_NUMBER = 23;
      private com.google.protobuf.ByteString cardHolderIDType_;
      /**
       * <pre>
       *持卡人证件类型
       * </pre>
       *
       * <code>optional bytes cardHolderIDType = 23;</code>
       */
      public com.google.protobuf.ByteString getCardHolderIDType() {
        return cardHolderIDType_;
      }

      public static final int OBUINFO_FIELD_NUMBER = 24;
      private com.google.protobuf.ByteString obuInfo_;
      /**
       * <pre>
       *OBU信息,合同
       * </pre>
       *
       * <code>optional bytes obuInfo = 24;</code>
       */
      public com.google.protobuf.ByteString getObuInfo() {
        return obuInfo_;
      }

      public static final int FILE0019_FIELD_NUMBER = 25;
      private com.google.protobuf.ByteString file0019_;
      /**
       * <pre>
       *文件0019，高速最后收费站信息
       * </pre>
       *
       * <code>optional bytes file0019 = 25;</code>
       */
      public com.google.protobuf.ByteString getFile0019() {
        return file0019_;
      }

      public static final int OBUTYPE_FIELD_NUMBER = 26;
      private com.google.protobuf.ByteString obuType_;
      /**
       * <pre>
       * obu类型
       * </pre>
       *
       * <code>optional bytes obuType = 26;</code>
       */
      public com.google.protobuf.ByteString getObuType() {
        return obuType_;
      }

      public static final int GPS_FIELD_NUMBER = 27;
      private com.google.protobuf.ByteString gps_;
      /**
       * <pre>
       *经纬度信息
       * </pre>
       *
       * <code>optional bytes gps = 27;</code>
       */
      public com.google.protobuf.ByteString getGps() {
        return gps_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!ubMac_.isEmpty()) {
          output.writeBytes(1, ubMac_);
        }
        if (time_ != 0) {
          output.writeUInt32(2, time_);
        }
        if (!cardIssuerID_.isEmpty()) {
          output.writeBytes(10, cardIssuerID_);
        }
        if (!cardType_.isEmpty()) {
          output.writeBytes(11, cardType_);
        }
        if (!cardVer_.isEmpty()) {
          output.writeBytes(12, cardVer_);
        }
        if (!cardNetID_.isEmpty()) {
          output.writeBytes(13, cardNetID_);
        }
        if (!cardInternalID_.isEmpty()) {
          output.writeBytes(14, cardInternalID_);
        }
        if (!enableTime_.isEmpty()) {
          output.writeBytes(15, enableTime_);
        }
        if (!expiredTime_.isEmpty()) {
          output.writeBytes(16, expiredTime_);
        }
        if (!carNO_.isEmpty()) {
          output.writeBytes(17, carNO_);
        }
        if (!userType_.isEmpty()) {
          output.writeBytes(18, userType_);
        }
        if (!carColor_.isEmpty()) {
          output.writeBytes(19, carColor_);
        }
        if (!carModel_.isEmpty()) {
          output.writeBytes(20, carModel_);
        }
        if (!cardHolderName_.isEmpty()) {
          output.writeBytes(21, cardHolderName_);
        }
        if (!cardHolderID_.isEmpty()) {
          output.writeBytes(22, cardHolderID_);
        }
        if (!cardHolderIDType_.isEmpty()) {
          output.writeBytes(23, cardHolderIDType_);
        }
        if (!obuInfo_.isEmpty()) {
          output.writeBytes(24, obuInfo_);
        }
        if (!file0019_.isEmpty()) {
          output.writeBytes(25, file0019_);
        }
        if (!obuType_.isEmpty()) {
          output.writeBytes(26, obuType_);
        }
        if (!gps_.isEmpty()) {
          output.writeBytes(27, gps_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!ubMac_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, ubMac_);
        }
        if (time_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, time_);
        }
        if (!cardIssuerID_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(10, cardIssuerID_);
        }
        if (!cardType_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(11, cardType_);
        }
        if (!cardVer_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(12, cardVer_);
        }
        if (!cardNetID_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(13, cardNetID_);
        }
        if (!cardInternalID_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(14, cardInternalID_);
        }
        if (!enableTime_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(15, enableTime_);
        }
        if (!expiredTime_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(16, expiredTime_);
        }
        if (!carNO_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(17, carNO_);
        }
        if (!userType_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(18, userType_);
        }
        if (!carColor_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(19, carColor_);
        }
        if (!carModel_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(20, carModel_);
        }
        if (!cardHolderName_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(21, cardHolderName_);
        }
        if (!cardHolderID_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(22, cardHolderID_);
        }
        if (!cardHolderIDType_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(23, cardHolderIDType_);
        }
        if (!obuInfo_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(24, obuInfo_);
        }
        if (!file0019_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(25, file0019_);
        }
        if (!obuType_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(26, obuType_);
        }
        if (!gps_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(27, gps_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof InfosETC.Infos.Information)) {
          return super.equals(obj);
        }
        InfosETC.Infos.Information other = (InfosETC.Infos.Information) obj;

        boolean result = true;
        result = result && getUbMac()
            .equals(other.getUbMac());
        result = result && (getTime()
            == other.getTime());
        result = result && getCardIssuerID()
            .equals(other.getCardIssuerID());
        result = result && getCardType()
            .equals(other.getCardType());
        result = result && getCardVer()
            .equals(other.getCardVer());
        result = result && getCardNetID()
            .equals(other.getCardNetID());
        result = result && getCardInternalID()
            .equals(other.getCardInternalID());
        result = result && getEnableTime()
            .equals(other.getEnableTime());
        result = result && getExpiredTime()
            .equals(other.getExpiredTime());
        result = result && getCarNO()
            .equals(other.getCarNO());
        result = result && getUserType()
            .equals(other.getUserType());
        result = result && getCarColor()
            .equals(other.getCarColor());
        result = result && getCarModel()
            .equals(other.getCarModel());
        result = result && getCardHolderName()
            .equals(other.getCardHolderName());
        result = result && getCardHolderID()
            .equals(other.getCardHolderID());
        result = result && getCardHolderIDType()
            .equals(other.getCardHolderIDType());
        result = result && getObuInfo()
            .equals(other.getObuInfo());
        result = result && getFile0019()
            .equals(other.getFile0019());
        result = result && getObuType()
            .equals(other.getObuType());
        result = result && getGps()
            .equals(other.getGps());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + UBMAC_FIELD_NUMBER;
        hash = (53 * hash) + getUbMac().hashCode();
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime();
        hash = (37 * hash) + CARDISSUERID_FIELD_NUMBER;
        hash = (53 * hash) + getCardIssuerID().hashCode();
        hash = (37 * hash) + CARDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCardType().hashCode();
        hash = (37 * hash) + CARDVER_FIELD_NUMBER;
        hash = (53 * hash) + getCardVer().hashCode();
        hash = (37 * hash) + CARDNETID_FIELD_NUMBER;
        hash = (53 * hash) + getCardNetID().hashCode();
        hash = (37 * hash) + CARDINTERNALID_FIELD_NUMBER;
        hash = (53 * hash) + getCardInternalID().hashCode();
        hash = (37 * hash) + ENABLETIME_FIELD_NUMBER;
        hash = (53 * hash) + getEnableTime().hashCode();
        hash = (37 * hash) + EXPIREDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getExpiredTime().hashCode();
        hash = (37 * hash) + CARNO_FIELD_NUMBER;
        hash = (53 * hash) + getCarNO().hashCode();
        hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getUserType().hashCode();
        hash = (37 * hash) + CARCOLOR_FIELD_NUMBER;
        hash = (53 * hash) + getCarColor().hashCode();
        hash = (37 * hash) + CARMODEL_FIELD_NUMBER;
        hash = (53 * hash) + getCarModel().hashCode();
        hash = (37 * hash) + CARDHOLDERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getCardHolderName().hashCode();
        hash = (37 * hash) + CARDHOLDERID_FIELD_NUMBER;
        hash = (53 * hash) + getCardHolderID().hashCode();
        hash = (37 * hash) + CARDHOLDERIDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCardHolderIDType().hashCode();
        hash = (37 * hash) + OBUINFO_FIELD_NUMBER;
        hash = (53 * hash) + getObuInfo().hashCode();
        hash = (37 * hash) + FILE0019_FIELD_NUMBER;
        hash = (53 * hash) + getFile0019().hashCode();
        hash = (37 * hash) + OBUTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getObuType().hashCode();
        hash = (37 * hash) + GPS_FIELD_NUMBER;
        hash = (53 * hash) + getGps().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static InfosETC.Infos.Information parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static InfosETC.Infos.Information parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static InfosETC.Infos.Information parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static InfosETC.Infos.Information parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static InfosETC.Infos.Information parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static InfosETC.Infos.Information parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static InfosETC.Infos.Information parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static InfosETC.Infos.Information parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static InfosETC.Infos.Information parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static InfosETC.Infos.Information parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(InfosETC.Infos.Information prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Infos.Information}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Infos.Information)
          InfosETC.Infos.InformationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return InfosETC.internal_static_Infos_Information_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return InfosETC.internal_static_Infos_Information_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  InfosETC.Infos.Information.class, InfosETC.Infos.Information.Builder.class);
        }

        // Construct using InfosETC.Infos.Information.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          ubMac_ = com.google.protobuf.ByteString.EMPTY;

          time_ = 0;

          cardIssuerID_ = com.google.protobuf.ByteString.EMPTY;

          cardType_ = com.google.protobuf.ByteString.EMPTY;

          cardVer_ = com.google.protobuf.ByteString.EMPTY;

          cardNetID_ = com.google.protobuf.ByteString.EMPTY;

          cardInternalID_ = com.google.protobuf.ByteString.EMPTY;

          enableTime_ = com.google.protobuf.ByteString.EMPTY;

          expiredTime_ = com.google.protobuf.ByteString.EMPTY;

          carNO_ = com.google.protobuf.ByteString.EMPTY;

          userType_ = com.google.protobuf.ByteString.EMPTY;

          carColor_ = com.google.protobuf.ByteString.EMPTY;

          carModel_ = com.google.protobuf.ByteString.EMPTY;

          cardHolderName_ = com.google.protobuf.ByteString.EMPTY;

          cardHolderID_ = com.google.protobuf.ByteString.EMPTY;

          cardHolderIDType_ = com.google.protobuf.ByteString.EMPTY;

          obuInfo_ = com.google.protobuf.ByteString.EMPTY;

          file0019_ = com.google.protobuf.ByteString.EMPTY;

          obuType_ = com.google.protobuf.ByteString.EMPTY;

          gps_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return InfosETC.internal_static_Infos_Information_descriptor;
        }

        public InfosETC.Infos.Information getDefaultInstanceForType() {
          return InfosETC.Infos.Information.getDefaultInstance();
        }

        public InfosETC.Infos.Information build() {
          InfosETC.Infos.Information result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public InfosETC.Infos.Information buildPartial() {
          InfosETC.Infos.Information result = new InfosETC.Infos.Information(this);
          result.ubMac_ = ubMac_;
          result.time_ = time_;
          result.cardIssuerID_ = cardIssuerID_;
          result.cardType_ = cardType_;
          result.cardVer_ = cardVer_;
          result.cardNetID_ = cardNetID_;
          result.cardInternalID_ = cardInternalID_;
          result.enableTime_ = enableTime_;
          result.expiredTime_ = expiredTime_;
          result.carNO_ = carNO_;
          result.userType_ = userType_;
          result.carColor_ = carColor_;
          result.carModel_ = carModel_;
          result.cardHolderName_ = cardHolderName_;
          result.cardHolderID_ = cardHolderID_;
          result.cardHolderIDType_ = cardHolderIDType_;
          result.obuInfo_ = obuInfo_;
          result.file0019_ = file0019_;
          result.obuType_ = obuType_;
          result.gps_ = gps_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof InfosETC.Infos.Information) {
            return mergeFrom((InfosETC.Infos.Information)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(InfosETC.Infos.Information other) {
          if (other == InfosETC.Infos.Information.getDefaultInstance()) return this;
          if (other.getUbMac() != com.google.protobuf.ByteString.EMPTY) {
            setUbMac(other.getUbMac());
          }
          if (other.getTime() != 0) {
            setTime(other.getTime());
          }
          if (other.getCardIssuerID() != com.google.protobuf.ByteString.EMPTY) {
            setCardIssuerID(other.getCardIssuerID());
          }
          if (other.getCardType() != com.google.protobuf.ByteString.EMPTY) {
            setCardType(other.getCardType());
          }
          if (other.getCardVer() != com.google.protobuf.ByteString.EMPTY) {
            setCardVer(other.getCardVer());
          }
          if (other.getCardNetID() != com.google.protobuf.ByteString.EMPTY) {
            setCardNetID(other.getCardNetID());
          }
          if (other.getCardInternalID() != com.google.protobuf.ByteString.EMPTY) {
            setCardInternalID(other.getCardInternalID());
          }
          if (other.getEnableTime() != com.google.protobuf.ByteString.EMPTY) {
            setEnableTime(other.getEnableTime());
          }
          if (other.getExpiredTime() != com.google.protobuf.ByteString.EMPTY) {
            setExpiredTime(other.getExpiredTime());
          }
          if (other.getCarNO() != com.google.protobuf.ByteString.EMPTY) {
            setCarNO(other.getCarNO());
          }
          if (other.getUserType() != com.google.protobuf.ByteString.EMPTY) {
            setUserType(other.getUserType());
          }
          if (other.getCarColor() != com.google.protobuf.ByteString.EMPTY) {
            setCarColor(other.getCarColor());
          }
          if (other.getCarModel() != com.google.protobuf.ByteString.EMPTY) {
            setCarModel(other.getCarModel());
          }
          if (other.getCardHolderName() != com.google.protobuf.ByteString.EMPTY) {
            setCardHolderName(other.getCardHolderName());
          }
          if (other.getCardHolderID() != com.google.protobuf.ByteString.EMPTY) {
            setCardHolderID(other.getCardHolderID());
          }
          if (other.getCardHolderIDType() != com.google.protobuf.ByteString.EMPTY) {
            setCardHolderIDType(other.getCardHolderIDType());
          }
          if (other.getObuInfo() != com.google.protobuf.ByteString.EMPTY) {
            setObuInfo(other.getObuInfo());
          }
          if (other.getFile0019() != com.google.protobuf.ByteString.EMPTY) {
            setFile0019(other.getFile0019());
          }
          if (other.getObuType() != com.google.protobuf.ByteString.EMPTY) {
            setObuType(other.getObuType());
          }
          if (other.getGps() != com.google.protobuf.ByteString.EMPTY) {
            setGps(other.getGps());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          InfosETC.Infos.Information parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (InfosETC.Infos.Information) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.google.protobuf.ByteString ubMac_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes ubMac = 1;</code>
         */
        public com.google.protobuf.ByteString getUbMac() {
          return ubMac_;
        }
        /**
         * <code>optional bytes ubMac = 1;</code>
         */
        public Builder setUbMac(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          ubMac_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes ubMac = 1;</code>
         */
        public Builder clearUbMac() {
          
          ubMac_ = getDefaultInstance().getUbMac();
          onChanged();
          return this;
        }

        private int time_ ;
        /**
         * <code>optional uint32 time = 2;</code>
         */
        public int getTime() {
          return time_;
        }
        /**
         * <code>optional uint32 time = 2;</code>
         */
        public Builder setTime(int value) {
          
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 time = 2;</code>
         */
        public Builder clearTime() {
          
          time_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardIssuerID_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *发卡方标识
         * </pre>
         *
         * <code>optional bytes cardIssuerID = 10;</code>
         */
        public com.google.protobuf.ByteString getCardIssuerID() {
          return cardIssuerID_;
        }
        /**
         * <pre>
         *发卡方标识
         * </pre>
         *
         * <code>optional bytes cardIssuerID = 10;</code>
         */
        public Builder setCardIssuerID(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardIssuerID_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *发卡方标识
         * </pre>
         *
         * <code>optional bytes cardIssuerID = 10;</code>
         */
        public Builder clearCardIssuerID() {
          
          cardIssuerID_ = getDefaultInstance().getCardIssuerID();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardType_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *卡片类型
         * </pre>
         *
         * <code>optional bytes cardType = 11;</code>
         */
        public com.google.protobuf.ByteString getCardType() {
          return cardType_;
        }
        /**
         * <pre>
         *卡片类型
         * </pre>
         *
         * <code>optional bytes cardType = 11;</code>
         */
        public Builder setCardType(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *卡片类型
         * </pre>
         *
         * <code>optional bytes cardType = 11;</code>
         */
        public Builder clearCardType() {
          
          cardType_ = getDefaultInstance().getCardType();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardVer_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *卡片版本号
         * </pre>
         *
         * <code>optional bytes cardVer = 12;</code>
         */
        public com.google.protobuf.ByteString getCardVer() {
          return cardVer_;
        }
        /**
         * <pre>
         *卡片版本号
         * </pre>
         *
         * <code>optional bytes cardVer = 12;</code>
         */
        public Builder setCardVer(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardVer_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *卡片版本号
         * </pre>
         *
         * <code>optional bytes cardVer = 12;</code>
         */
        public Builder clearCardVer() {
          
          cardVer_ = getDefaultInstance().getCardVer();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardNetID_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *卡片网络编号
         * </pre>
         *
         * <code>optional bytes cardNetID = 13;</code>
         */
        public com.google.protobuf.ByteString getCardNetID() {
          return cardNetID_;
        }
        /**
         * <pre>
         *卡片网络编号
         * </pre>
         *
         * <code>optional bytes cardNetID = 13;</code>
         */
        public Builder setCardNetID(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardNetID_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *卡片网络编号
         * </pre>
         *
         * <code>optional bytes cardNetID = 13;</code>
         */
        public Builder clearCardNetID() {
          
          cardNetID_ = getDefaultInstance().getCardNetID();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardInternalID_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *用户卡内部编号
         * </pre>
         *
         * <code>optional bytes cardInternalID = 14;</code>
         */
        public com.google.protobuf.ByteString getCardInternalID() {
          return cardInternalID_;
        }
        /**
         * <pre>
         *用户卡内部编号
         * </pre>
         *
         * <code>optional bytes cardInternalID = 14;</code>
         */
        public Builder setCardInternalID(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardInternalID_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户卡内部编号
         * </pre>
         *
         * <code>optional bytes cardInternalID = 14;</code>
         */
        public Builder clearCardInternalID() {
          
          cardInternalID_ = getDefaultInstance().getCardInternalID();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString enableTime_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *启用时间
         * </pre>
         *
         * <code>optional bytes enableTime = 15;</code>
         */
        public com.google.protobuf.ByteString getEnableTime() {
          return enableTime_;
        }
        /**
         * <pre>
         *启用时间
         * </pre>
         *
         * <code>optional bytes enableTime = 15;</code>
         */
        public Builder setEnableTime(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          enableTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *启用时间
         * </pre>
         *
         * <code>optional bytes enableTime = 15;</code>
         */
        public Builder clearEnableTime() {
          
          enableTime_ = getDefaultInstance().getEnableTime();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString expiredTime_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *到期时间
         * </pre>
         *
         * <code>optional bytes expiredTime = 16;</code>
         */
        public com.google.protobuf.ByteString getExpiredTime() {
          return expiredTime_;
        }
        /**
         * <pre>
         *到期时间
         * </pre>
         *
         * <code>optional bytes expiredTime = 16;</code>
         */
        public Builder setExpiredTime(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          expiredTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *到期时间
         * </pre>
         *
         * <code>optional bytes expiredTime = 16;</code>
         */
        public Builder clearExpiredTime() {
          
          expiredTime_ = getDefaultInstance().getExpiredTime();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString carNO_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *	车牌号码
         * </pre>
         *
         * <code>optional bytes carNO = 17;</code>
         */
        public com.google.protobuf.ByteString getCarNO() {
          return carNO_;
        }
        /**
         * <pre>
         *	车牌号码
         * </pre>
         *
         * <code>optional bytes carNO = 17;</code>
         */
        public Builder setCarNO(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          carNO_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *	车牌号码
         * </pre>
         *
         * <code>optional bytes carNO = 17;</code>
         */
        public Builder clearCarNO() {
          
          carNO_ = getDefaultInstance().getCarNO();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString userType_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *用户类型
         * </pre>
         *
         * <code>optional bytes userType = 18;</code>
         */
        public com.google.protobuf.ByteString getUserType() {
          return userType_;
        }
        /**
         * <pre>
         *用户类型
         * </pre>
         *
         * <code>optional bytes userType = 18;</code>
         */
        public Builder setUserType(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          userType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户类型
         * </pre>
         *
         * <code>optional bytes userType = 18;</code>
         */
        public Builder clearUserType() {
          
          userType_ = getDefaultInstance().getUserType();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString carColor_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *	车牌颜色
         * </pre>
         *
         * <code>optional bytes carColor = 19;</code>
         */
        public com.google.protobuf.ByteString getCarColor() {
          return carColor_;
        }
        /**
         * <pre>
         *	车牌颜色
         * </pre>
         *
         * <code>optional bytes carColor = 19;</code>
         */
        public Builder setCarColor(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          carColor_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *	车牌颜色
         * </pre>
         *
         * <code>optional bytes carColor = 19;</code>
         */
        public Builder clearCarColor() {
          
          carColor_ = getDefaultInstance().getCarColor();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString carModel_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *车型
         * </pre>
         *
         * <code>optional bytes carModel = 20;</code>
         */
        public com.google.protobuf.ByteString getCarModel() {
          return carModel_;
        }
        /**
         * <pre>
         *车型
         * </pre>
         *
         * <code>optional bytes carModel = 20;</code>
         */
        public Builder setCarModel(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          carModel_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *车型
         * </pre>
         *
         * <code>optional bytes carModel = 20;</code>
         */
        public Builder clearCarModel() {
          
          carModel_ = getDefaultInstance().getCarModel();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardHolderName_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *持卡人姓名
         * </pre>
         *
         * <code>optional bytes cardHolderName = 21;</code>
         */
        public com.google.protobuf.ByteString getCardHolderName() {
          return cardHolderName_;
        }
        /**
         * <pre>
         *持卡人姓名
         * </pre>
         *
         * <code>optional bytes cardHolderName = 21;</code>
         */
        public Builder setCardHolderName(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardHolderName_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *持卡人姓名
         * </pre>
         *
         * <code>optional bytes cardHolderName = 21;</code>
         */
        public Builder clearCardHolderName() {
          
          cardHolderName_ = getDefaultInstance().getCardHolderName();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardHolderID_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *持卡人证件号码
         * </pre>
         *
         * <code>optional bytes cardHolderID = 22;</code>
         */
        public com.google.protobuf.ByteString getCardHolderID() {
          return cardHolderID_;
        }
        /**
         * <pre>
         *持卡人证件号码
         * </pre>
         *
         * <code>optional bytes cardHolderID = 22;</code>
         */
        public Builder setCardHolderID(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardHolderID_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *持卡人证件号码
         * </pre>
         *
         * <code>optional bytes cardHolderID = 22;</code>
         */
        public Builder clearCardHolderID() {
          
          cardHolderID_ = getDefaultInstance().getCardHolderID();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString cardHolderIDType_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *持卡人证件类型
         * </pre>
         *
         * <code>optional bytes cardHolderIDType = 23;</code>
         */
        public com.google.protobuf.ByteString getCardHolderIDType() {
          return cardHolderIDType_;
        }
        /**
         * <pre>
         *持卡人证件类型
         * </pre>
         *
         * <code>optional bytes cardHolderIDType = 23;</code>
         */
        public Builder setCardHolderIDType(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cardHolderIDType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *持卡人证件类型
         * </pre>
         *
         * <code>optional bytes cardHolderIDType = 23;</code>
         */
        public Builder clearCardHolderIDType() {
          
          cardHolderIDType_ = getDefaultInstance().getCardHolderIDType();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString obuInfo_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *OBU信息,合同
         * </pre>
         *
         * <code>optional bytes obuInfo = 24;</code>
         */
        public com.google.protobuf.ByteString getObuInfo() {
          return obuInfo_;
        }
        /**
         * <pre>
         *OBU信息,合同
         * </pre>
         *
         * <code>optional bytes obuInfo = 24;</code>
         */
        public Builder setObuInfo(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          obuInfo_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *OBU信息,合同
         * </pre>
         *
         * <code>optional bytes obuInfo = 24;</code>
         */
        public Builder clearObuInfo() {
          
          obuInfo_ = getDefaultInstance().getObuInfo();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString file0019_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *文件0019，高速最后收费站信息
         * </pre>
         *
         * <code>optional bytes file0019 = 25;</code>
         */
        public com.google.protobuf.ByteString getFile0019() {
          return file0019_;
        }
        /**
         * <pre>
         *文件0019，高速最后收费站信息
         * </pre>
         *
         * <code>optional bytes file0019 = 25;</code>
         */
        public Builder setFile0019(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          file0019_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *文件0019，高速最后收费站信息
         * </pre>
         *
         * <code>optional bytes file0019 = 25;</code>
         */
        public Builder clearFile0019() {
          
          file0019_ = getDefaultInstance().getFile0019();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString obuType_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         * obu类型
         * </pre>
         *
         * <code>optional bytes obuType = 26;</code>
         */
        public com.google.protobuf.ByteString getObuType() {
          return obuType_;
        }
        /**
         * <pre>
         * obu类型
         * </pre>
         *
         * <code>optional bytes obuType = 26;</code>
         */
        public Builder setObuType(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          obuType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * obu类型
         * </pre>
         *
         * <code>optional bytes obuType = 26;</code>
         */
        public Builder clearObuType() {
          
          obuType_ = getDefaultInstance().getObuType();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString gps_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         *经纬度信息
         * </pre>
         *
         * <code>optional bytes gps = 27;</code>
         */
        public com.google.protobuf.ByteString getGps() {
          return gps_;
        }
        /**
         * <pre>
         *经纬度信息
         * </pre>
         *
         * <code>optional bytes gps = 27;</code>
         */
        public Builder setGps(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          gps_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *经纬度信息
         * </pre>
         *
         * <code>optional bytes gps = 27;</code>
         */
        public Builder clearGps() {
          
          gps_ = getDefaultInstance().getGps();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:Infos.Information)
      }

      // @@protoc_insertion_point(class_scope:Infos.Information)
      private static final InfosETC.Infos.Information DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new InfosETC.Infos.Information();
      }

      public static InfosETC.Infos.Information getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Information>
          PARSER = new com.google.protobuf.AbstractParser<Information>() {
        public Information parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Information(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Information> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Information> getParserForType() {
        return PARSER;
      }

      public InfosETC.Infos.Information getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int INFORMATION_FIELD_NUMBER = 1;
    private java.util.List<InfosETC.Infos.Information> information_;
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    public java.util.List<InfosETC.Infos.Information> getInformationList() {
      return information_;
    }
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    public java.util.List<? extends InfosETC.Infos.InformationOrBuilder> 
        getInformationOrBuilderList() {
      return information_;
    }
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    public int getInformationCount() {
      return information_.size();
    }
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    public InfosETC.Infos.Information getInformation(int index) {
      return information_.get(index);
    }
    /**
     * <code>repeated .Infos.Information information = 1;</code>
     */
    public InfosETC.Infos.InformationOrBuilder getInformationOrBuilder(
        int index) {
      return information_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < information_.size(); i++) {
        output.writeMessage(1, information_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < information_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, information_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InfosETC.Infos)) {
        return super.equals(obj);
      }
      InfosETC.Infos other = (InfosETC.Infos) obj;

      boolean result = true;
      result = result && getInformationList()
          .equals(other.getInformationList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getInformationCount() > 0) {
        hash = (37 * hash) + INFORMATION_FIELD_NUMBER;
        hash = (53 * hash) + getInformationList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InfosETC.Infos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InfosETC.Infos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InfosETC.Infos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InfosETC.Infos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InfosETC.Infos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static InfosETC.Infos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InfosETC.Infos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InfosETC.Infos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InfosETC.Infos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static InfosETC.Infos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InfosETC.Infos prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Infos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Infos)
        InfosETC.InfosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InfosETC.internal_static_Infos_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InfosETC.internal_static_Infos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InfosETC.Infos.class, InfosETC.Infos.Builder.class);
      }

      // Construct using InfosETC.Infos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInformationFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (informationBuilder_ == null) {
          information_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          informationBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InfosETC.internal_static_Infos_descriptor;
      }

      public InfosETC.Infos getDefaultInstanceForType() {
        return InfosETC.Infos.getDefaultInstance();
      }

      public InfosETC.Infos build() {
        InfosETC.Infos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public InfosETC.Infos buildPartial() {
        InfosETC.Infos result = new InfosETC.Infos(this);
        int from_bitField0_ = bitField0_;
        if (informationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            information_ = java.util.Collections.unmodifiableList(information_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.information_ = information_;
        } else {
          result.information_ = informationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InfosETC.Infos) {
          return mergeFrom((InfosETC.Infos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InfosETC.Infos other) {
        if (other == InfosETC.Infos.getDefaultInstance()) return this;
        if (informationBuilder_ == null) {
          if (!other.information_.isEmpty()) {
            if (information_.isEmpty()) {
              information_ = other.information_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInformationIsMutable();
              information_.addAll(other.information_);
            }
            onChanged();
          }
        } else {
          if (!other.information_.isEmpty()) {
            if (informationBuilder_.isEmpty()) {
              informationBuilder_.dispose();
              informationBuilder_ = null;
              information_ = other.information_;
              bitField0_ = (bitField0_ & ~0x00000001);
              informationBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInformationFieldBuilder() : null;
            } else {
              informationBuilder_.addAllMessages(other.information_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InfosETC.Infos parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InfosETC.Infos) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<InfosETC.Infos.Information> information_ =
        java.util.Collections.emptyList();
      private void ensureInformationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          information_ = new java.util.ArrayList<InfosETC.Infos.Information>(information_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          InfosETC.Infos.Information, InfosETC.Infos.Information.Builder, InfosETC.Infos.InformationOrBuilder> informationBuilder_;

      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public java.util.List<InfosETC.Infos.Information> getInformationList() {
        if (informationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(information_);
        } else {
          return informationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public int getInformationCount() {
        if (informationBuilder_ == null) {
          return information_.size();
        } else {
          return informationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public InfosETC.Infos.Information getInformation(int index) {
        if (informationBuilder_ == null) {
          return information_.get(index);
        } else {
          return informationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder setInformation(
          int index, InfosETC.Infos.Information value) {
        if (informationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInformationIsMutable();
          information_.set(index, value);
          onChanged();
        } else {
          informationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder setInformation(
          int index, InfosETC.Infos.Information.Builder builderForValue) {
        if (informationBuilder_ == null) {
          ensureInformationIsMutable();
          information_.set(index, builderForValue.build());
          onChanged();
        } else {
          informationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder addInformation(InfosETC.Infos.Information value) {
        if (informationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInformationIsMutable();
          information_.add(value);
          onChanged();
        } else {
          informationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder addInformation(
          int index, InfosETC.Infos.Information value) {
        if (informationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInformationIsMutable();
          information_.add(index, value);
          onChanged();
        } else {
          informationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder addInformation(
          InfosETC.Infos.Information.Builder builderForValue) {
        if (informationBuilder_ == null) {
          ensureInformationIsMutable();
          information_.add(builderForValue.build());
          onChanged();
        } else {
          informationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder addInformation(
          int index, InfosETC.Infos.Information.Builder builderForValue) {
        if (informationBuilder_ == null) {
          ensureInformationIsMutable();
          information_.add(index, builderForValue.build());
          onChanged();
        } else {
          informationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder addAllInformation(
          java.lang.Iterable<? extends InfosETC.Infos.Information> values) {
        if (informationBuilder_ == null) {
          ensureInformationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, information_);
          onChanged();
        } else {
          informationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder clearInformation() {
        if (informationBuilder_ == null) {
          information_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          informationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public Builder removeInformation(int index) {
        if (informationBuilder_ == null) {
          ensureInformationIsMutable();
          information_.remove(index);
          onChanged();
        } else {
          informationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public InfosETC.Infos.Information.Builder getInformationBuilder(
          int index) {
        return getInformationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public InfosETC.Infos.InformationOrBuilder getInformationOrBuilder(
          int index) {
        if (informationBuilder_ == null) {
          return information_.get(index);  } else {
          return informationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public java.util.List<? extends InfosETC.Infos.InformationOrBuilder> 
           getInformationOrBuilderList() {
        if (informationBuilder_ != null) {
          return informationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(information_);
        }
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public InfosETC.Infos.Information.Builder addInformationBuilder() {
        return getInformationFieldBuilder().addBuilder(
            InfosETC.Infos.Information.getDefaultInstance());
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public InfosETC.Infos.Information.Builder addInformationBuilder(
          int index) {
        return getInformationFieldBuilder().addBuilder(
            index, InfosETC.Infos.Information.getDefaultInstance());
      }
      /**
       * <code>repeated .Infos.Information information = 1;</code>
       */
      public java.util.List<InfosETC.Infos.Information.Builder> 
           getInformationBuilderList() {
        return getInformationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          InfosETC.Infos.Information, InfosETC.Infos.Information.Builder, InfosETC.Infos.InformationOrBuilder> 
          getInformationFieldBuilder() {
        if (informationBuilder_ == null) {
          informationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              InfosETC.Infos.Information, InfosETC.Infos.Information.Builder, InfosETC.Infos.InformationOrBuilder>(
                  information_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          information_ = null;
        }
        return informationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Infos)
    }

    // @@protoc_insertion_point(class_scope:Infos)
    private static final InfosETC.Infos DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InfosETC.Infos();
    }

    public static InfosETC.Infos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Infos>
        PARSER = new com.google.protobuf.AbstractParser<Infos>() {
      public Infos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Infos(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Infos> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Infos> getParserForType() {
      return PARSER;
    }

    public InfosETC.Infos getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Infos_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Infos_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Infos_Information_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Infos_Information_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Infos-ETC.proto\"\270\003\n\005Infos\022\'\n\013informati" +
      "on\030\001 \003(\0132\022.Infos.Information\032\205\003\n\013Informa" +
      "tion\022\r\n\005ubMac\030\001 \001(\014\022\014\n\004time\030\002 \001(\r\022\024\n\014car" +
      "dIssuerID\030\n \001(\014\022\020\n\010cardType\030\013 \001(\014\022\017\n\007car" +
      "dVer\030\014 \001(\014\022\021\n\tcardNetID\030\r \001(\014\022\026\n\016cardInt" +
      "ernalID\030\016 \001(\014\022\022\n\nenableTime\030\017 \001(\014\022\023\n\013exp" +
      "iredTime\030\020 \001(\014\022\r\n\005carNO\030\021 \001(\014\022\020\n\010userTyp" +
      "e\030\022 \001(\014\022\020\n\010carColor\030\023 \001(\014\022\020\n\010carModel\030\024 " +
      "\001(\014\022\026\n\016cardHolderName\030\025 \001(\014\022\024\n\014cardHolde" +
      "rID\030\026 \001(\014\022\030\n\020cardHolderIDType\030\027 \001(\014\022\017\n\007o",
      "buInfo\030\030 \001(\014\022\020\n\010file0019\030\031 \001(\014\022\017\n\007obuTyp" +
      "e\030\032 \001(\014\022\013\n\003gps\030\033 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Infos_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Infos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Infos_descriptor,
        new java.lang.String[] { "Information", });
    internal_static_Infos_Information_descriptor =
      internal_static_Infos_descriptor.getNestedTypes().get(0);
    internal_static_Infos_Information_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Infos_Information_descriptor,
        new java.lang.String[] { "UbMac", "Time", "CardIssuerID", "CardType", "CardVer", "CardNetID", "CardInternalID", "EnableTime", "ExpiredTime", "CarNO", "UserType", "CarColor", "CarModel", "CardHolderName", "CardHolderID", "CardHolderIDType", "ObuInfo", "File0019", "ObuType", "Gps", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
