/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Information.proto */

#ifndef PROTOBUF_C_Information_2eproto__INCLUDED
#define PROTOBUF_C_Information_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Information Information;
typedef struct _Information__UserInformation Information__UserInformation;
typedef struct _Information__CardInformation Information__CardInformation;
typedef struct _RepeatedInformation RepeatedInformation;


/* --- enums --- */


/* --- messages --- */

struct  _Information__UserInformation
{
  ProtobufCMessage base;
  protobuf_c_boolean has_oweridentifier;
  uint32_t oweridentifier;
  protobuf_c_boolean has_staffidentifier;
  uint32_t staffidentifier;
  char *owername;
  char *owercertificatenum;
  protobuf_c_boolean has_owercertificatetype;
  uint32_t owercertificatetype;
};
#define INFORMATION__USER_INFORMATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&information__user_information__descriptor) \
    , 0, 0, 0, 0, NULL, NULL, 0, 0 }


struct  _Information__CardInformation
{
  ProtobufCMessage base;
  char *cardissueridentifier;
  protobuf_c_boolean has_cardtype;
  uint32_t cardtype;
  protobuf_c_boolean has_cardversion;
  uint32_t cardversion;
  protobuf_c_boolean has_cardnetworknum;
  uint32_t cardnetworknum;
  protobuf_c_boolean has_carduserinternalnum;
  uint32_t carduserinternalnum;
  char *enabledtime;
  char *expiretime;
  char *carplatenumber;
  protobuf_c_boolean has_usertype;
  uint32_t usertype;
  protobuf_c_boolean has_carplatecolor;
  uint32_t carplatecolor;
  protobuf_c_boolean has_carmodel;
  uint32_t carmodel;
};
#define INFORMATION__CARD_INFORMATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&information__card_information__descriptor) \
    , NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0 }


struct  _Information
{
  ProtobufCMessage base;
  Information__UserInformation *userinfo;
  Information__CardInformation *cardinfo;
};
#define INFORMATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&information__descriptor) \
    , NULL, NULL }


struct  _RepeatedInformation
{
  ProtobufCMessage base;
  size_t n_infos;
  Information **infos;
};
#define REPEATED_INFORMATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&repeated_information__descriptor) \
    , 0,NULL }


/* Information__UserInformation methods */
void   information__user_information__init
                     (Information__UserInformation         *message);
/* Information__CardInformation methods */
void   information__card_information__init
                     (Information__CardInformation         *message);
/* Information methods */
void   information__init
                     (Information         *message);
size_t information__get_packed_size
                     (const Information   *message);
size_t information__pack
                     (const Information   *message,
                      uint8_t             *out);
size_t information__pack_to_buffer
                     (const Information   *message,
                      ProtobufCBuffer     *buffer);
Information *
       information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   information__free_unpacked
                     (Information *message,
                      ProtobufCAllocator *allocator);
/* RepeatedInformation methods */
void   repeated_information__init
                     (RepeatedInformation         *message);
size_t repeated_information__get_packed_size
                     (const RepeatedInformation   *message);
size_t repeated_information__pack
                     (const RepeatedInformation   *message,
                      uint8_t             *out);
size_t repeated_information__pack_to_buffer
                     (const RepeatedInformation   *message,
                      ProtobufCBuffer     *buffer);
RepeatedInformation *
       repeated_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   repeated_information__free_unpacked
                     (RepeatedInformation *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Information__UserInformation_Closure)
                 (const Information__UserInformation *message,
                  void *closure_data);
typedef void (*Information__CardInformation_Closure)
                 (const Information__CardInformation *message,
                  void *closure_data);
typedef void (*Information_Closure)
                 (const Information *message,
                  void *closure_data);
typedef void (*RepeatedInformation_Closure)
                 (const RepeatedInformation *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor information__descriptor;
extern const ProtobufCMessageDescriptor information__user_information__descriptor;
extern const ProtobufCMessageDescriptor information__card_information__descriptor;
extern const ProtobufCMessageDescriptor repeated_information__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Information_2eproto__INCLUDED */
