/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Information.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Information.pb-c.h"
void   information__user_information__init
                     (Information__UserInformation         *message)
{
  static const Information__UserInformation init_value = INFORMATION__USER_INFORMATION__INIT;
  *message = init_value;
}
void   information__card_information__init
                     (Information__CardInformation         *message)
{
  static const Information__CardInformation init_value = INFORMATION__CARD_INFORMATION__INIT;
  *message = init_value;
}
void   information__init
                     (Information         *message)
{
  static const Information init_value = INFORMATION__INIT;
  *message = init_value;
}
size_t information__get_packed_size
                     (const Information *message)
{
  assert(message->base.descriptor == &information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t information__pack
                     (const Information *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t information__pack_to_buffer
                     (const Information *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Information *
       information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Information *)
     protobuf_c_message_unpack (&information__descriptor,
                                allocator, len, data);
}
void   information__free_unpacked
                     (Information *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   repeated_information__init
                     (RepeatedInformation         *message)
{
  static const RepeatedInformation init_value = REPEATED_INFORMATION__INIT;
  *message = init_value;
}
size_t repeated_information__get_packed_size
                     (const RepeatedInformation *message)
{
  assert(message->base.descriptor == &repeated_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t repeated_information__pack
                     (const RepeatedInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &repeated_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t repeated_information__pack_to_buffer
                     (const RepeatedInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &repeated_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RepeatedInformation *
       repeated_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RepeatedInformation *)
     protobuf_c_message_unpack (&repeated_information__descriptor,
                                allocator, len, data);
}
void   repeated_information__free_unpacked
                     (RepeatedInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &repeated_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor information__user_information__field_descriptors[5] =
{
  {
    "owerIdentifier",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__UserInformation, has_oweridentifier),
    offsetof(Information__UserInformation, oweridentifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "staffIdentifier",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__UserInformation, has_staffidentifier),
    offsetof(Information__UserInformation, staffidentifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owerName",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Information__UserInformation, owername),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owerCertificateNum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Information__UserInformation, owercertificatenum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owerCertificateType",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__UserInformation, has_owercertificatetype),
    offsetof(Information__UserInformation, owercertificatetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned information__user_information__field_indices_by_name[] = {
  3,   /* field[3] = owerCertificateNum */
  4,   /* field[4] = owerCertificateType */
  0,   /* field[0] = owerIdentifier */
  2,   /* field[2] = owerName */
  1,   /* field[1] = staffIdentifier */
};
static const ProtobufCIntRange information__user_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor information__user_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Information.UserInformation",
  "UserInformation",
  "Information__UserInformation",
  "",
  sizeof(Information__UserInformation),
  5,
  information__user_information__field_descriptors,
  information__user_information__field_indices_by_name,
  1,  information__user_information__number_ranges,
  (ProtobufCMessageInit) information__user_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor information__card_information__field_descriptors[11] =
{
  {
    "cardIssuerIdentifier",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Information__CardInformation, cardissueridentifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cardType",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__CardInformation, has_cardtype),
    offsetof(Information__CardInformation, cardtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cardVersion",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__CardInformation, has_cardversion),
    offsetof(Information__CardInformation, cardversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cardNetworkNum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__CardInformation, has_cardnetworknum),
    offsetof(Information__CardInformation, cardnetworknum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cardUserInternalNum",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__CardInformation, has_carduserinternalnum),
    offsetof(Information__CardInformation, carduserinternalnum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enabledTime",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Information__CardInformation, enabledtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expireTime",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Information__CardInformation, expiretime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "carPlateNumber",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Information__CardInformation, carplatenumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userType",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__CardInformation, has_usertype),
    offsetof(Information__CardInformation, usertype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "carPlateColor",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__CardInformation, has_carplatecolor),
    offsetof(Information__CardInformation, carplatecolor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "carModel",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Information__CardInformation, has_carmodel),
    offsetof(Information__CardInformation, carmodel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned information__card_information__field_indices_by_name[] = {
  10,   /* field[10] = carModel */
  9,   /* field[9] = carPlateColor */
  7,   /* field[7] = carPlateNumber */
  0,   /* field[0] = cardIssuerIdentifier */
  3,   /* field[3] = cardNetworkNum */
  1,   /* field[1] = cardType */
  4,   /* field[4] = cardUserInternalNum */
  2,   /* field[2] = cardVersion */
  5,   /* field[5] = enabledTime */
  6,   /* field[6] = expireTime */
  8,   /* field[8] = userType */
};
static const ProtobufCIntRange information__card_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor information__card_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Information.CardInformation",
  "CardInformation",
  "Information__CardInformation",
  "",
  sizeof(Information__CardInformation),
  11,
  information__card_information__field_descriptors,
  information__card_information__field_indices_by_name,
  1,  information__card_information__number_ranges,
  (ProtobufCMessageInit) information__card_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor information__field_descriptors[2] =
{
  {
    "userInfo",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Information, userinfo),
    &information__user_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cardInfo",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Information, cardinfo),
    &information__card_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned information__field_indices_by_name[] = {
  1,   /* field[1] = cardInfo */
  0,   /* field[0] = userInfo */
};
static const ProtobufCIntRange information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Information",
  "Information",
  "Information",
  "",
  sizeof(Information),
  2,
  information__field_descriptors,
  information__field_indices_by_name,
  1,  information__number_ranges,
  (ProtobufCMessageInit) information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor repeated_information__field_descriptors[1] =
{
  {
    "infos",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RepeatedInformation, n_infos),
    offsetof(RepeatedInformation, infos),
    &information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned repeated_information__field_indices_by_name[] = {
  0,   /* field[0] = infos */
};
static const ProtobufCIntRange repeated_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor repeated_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RepeatedInformation",
  "RepeatedInformation",
  "RepeatedInformation",
  "",
  sizeof(RepeatedInformation),
  1,
  repeated_information__field_descriptors,
  repeated_information__field_indices_by_name,
  1,  repeated_information__number_ranges,
  (ProtobufCMessageInit) repeated_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
